name: ci-cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        env:
          ENVIRONMENT: $${{ vars.ENVIRONMENT }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}
          BIND_URL: ${{ vars.BIND_URL }}
          BIND_PORT: ${{ vars.BIND_PORT }}
          PG_PORT: ${{ vars.PG_PORT }}
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          PG_USERNAME: ${{ secrets.PG_USERNAME }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
